openapi: 3.0.3
info:
  title: NeoTour Project
  version: 1.0.0
  description: NeoTour is an optimized application designed for convenient tour booking.
paths:
  /categories/:
    get:
      operationId: categories_retrieve
      tags:
      - categories
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /categories/{id}:
    get:
      operationId: categories_retrieve_2
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - categories
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /tours/:
    get:
      operationId: tours_retrieve
      tags:
      - tours
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /tours/{id}:
    get:
      operationId: tours_retrieve_2
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - tours
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
    post:
      operationId: tours_create
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - tours
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /tours/{id}/reservations:
    get:
      operationId: tours_reservations_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - tours
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /tours/{id}/reviews:
    get:
      operationId: tours_reviews_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - tours
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
    post:
      operationId: tours_reviews_create
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - tours
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /tours/recommended:
    get:
      operationId: tours_recommended_retrieve
      tags:
      - tours
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /tours/seasons:
    get:
      operationId: tours_seasons_retrieve
      tags:
      - tours
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
