# Generated by Django 5.0.2 on 2024-02-26 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TourCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('season', models.CharField(choices=[('Summer', 'Summer'), ('Fall', 'Fall'), ('Winter', 'Winter'), ('Spring', 'Spring')], default='Summer', max_length=200)),
                ('image', models.ImageField(upload_to='tour_photos')),
                ('is_recommended', models.BooleanField(default=False)),
                ('category', models.ManyToManyField(to='tours.tourcategories')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='user_photos')),
                ('review_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='tours.tours')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=30)),
                ('order_comment', models.TextField()),
                ('people_num', models.PositiveIntegerField(default=1)),
                ('tour_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.tours')),
            ],
        ),
    ]
