# Generated by Django 5.0.2 on 2024-02-27 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_alter_reviews_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='tour_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='tours.tours'),
        ),
    ]
