# Generated by Django 5.0.2 on 2024-02-27 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_alter_reservation_tour_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tours',
            name='category',
            field=models.ManyToManyField(related_name='tours', to='tours.tourcategories'),
        ),
    ]
